FROM node:lts-alpine as builder

WORKDIR /app

COPY frontend/ .

RUN npm install
RUN npm run build

FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /app/.output ./output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.nuxt ./.nuxt


# ENTRYPOINT [ "npm", "start" ]
ENTRYPOINT ["sleep", "infinity"]