FROM golang:1.25 AS builder

WORKDIR /app

COPY app/ .

RUN go mod tidy
RUN go build -o bin/scraper.bin ./cmd/scraper/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache chromium libc6-compat netcat-openbsd

COPY --from=builder /app/bin/scraper.bin scraper.bin
COPY --from=builder /app/go.mod go.mod
COPY docker/scripts/wait-for-postgres.sh wait-for-postgres.sh
COPY docker/scripts/entrypoint-scraper.sh entrypoint.sh

RUN chmod +x wait-for-postgres.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
