x-go-common: &x-go-common
  environment:
    LOG_FORMAT: json
  volumes:
    - ./app/resource:/app/resource
    - ./app/var:/app/var
    - ./app/config.json:/app/config.json
  networks:
    - app_network

services:
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s

  rabbitmq:
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  migrate:
    <<: *x-go-common
    build:
      context: .
      dockerfile: ./docker/golang/migrate/Dockerfile.prod
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./app/resource:/app/resource
      - ./app/var:/app/var
      - ./app/config.json:/app/config.json
      - ./app/migrations:/app/migrations

  app:
    <<: *x-go-common
    build:
      context: .
      dockerfile: ./docker/golang/api/Dockerfile.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  scraper:
    <<: *x-go-common
    build:
      context: .
      dockerfile: ./docker/golang/scraper/Dockerfile.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    shm_size: "1gb"

  notify:
    <<: *x-go-common
    build:
      context: .
      dockerfile: ./docker/golang/notify/Dockerfile.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: workspace-frontend
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile.prod
      args:
        NUXT_PUBLIC_API_BASE: http://localhost:8080/api
    depends_on:
      - app
    restart: always
    networks:
      - app_network

  nginx:
    depends_on:
      - app
      - frontend
