server {
	listen 80;
	server_name localhost;

	location /api/ {
		# te nagłówki?
		proxy_pass http://app:8080/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Connection 'Upgrade';
		client_max_body_size 100G;
		client_body_buffer_size 128k;
		proxy_connect_timeout 3600;
		proxy_send_timeout 3600;
		proxy_read_timeout 3600;
		fastcgi_buffers 16 16k;
		fastcgi_buffer_size 32k;
		proxy_buffer_size 128k;
		proxy_buffers 4 256k;
		proxy_busy_buffers_size 256k;
	}

	location /adminer/ {
		proxy_pass http://adminer:8080/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Connection 'Upgrade';
		proxy_read_timeout 3600;
	}

	# location /dashboard/ {
	# 	proxy_pass http://frontend:3000;
	# 	proxy_set_header Host $host;
	# 	proxy_set_header X-Real-IP $remote_addr;
	# 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# 	proxy_set_header Connection 'Upgrade';
	# 	proxy_set_header Upgrade $http_upgrade;
	# 	proxy_read_timeout 3600;
	# }

	location /mailhog/ {
		proxy_pass http://mailhog:8025/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Connection 'Upgrade';
		proxy_read_timeout 3600;
	}

	location /rabbitmq/ {
		proxy_pass http://rabbitmq:15672/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Connection 'Upgrade';
		proxy_read_timeout 3600;
	}
}