FROM golang:1.25 AS builder

WORKDIR /app

COPY app/ .

RUN go mod tidy
RUN go build -o bin/migrate.bin ./cmd/migrate/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY --from=builder /app/bin/migrate.bin migrate.bin
COPY --from=builder /app/config.example.json config.json
COPY --from=builder /app/go.mod go.mod
COPY --from=builder /app/migrations migrations/

ENTRYPOINT ["./migrate.bin"]
