FROM golang:1.25 AS builder

WORKDIR /app

COPY app/ .

RUN go mod tidy
RUN go build -o bin/api.bin ./cmd/api/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache libc6-compat netcat-openbsd

COPY --from=builder /app/bin/api.bin api.bin
COPY --from=builder /app/config.example.json config.json
COPY --from=builder /app/go.mod go.mod
COPY docker/scripts/wait-for-postgres.sh wait-for-postgres.sh
COPY docker/scripts/entrypoint-api.sh entrypoint.sh

RUN chmod +x wait-for-postgres.sh entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
